apiVersion: v1
kind: Service
metadata:
  name: {{ template "nexus.fullname" . }}
  labels:
{{ include "nexus.labels" . | indent 4 }}
spec:
  ports:
    - name: {{ .Values.nexus.name }}
      port: {{ .Values.nexus.port }}
      protocol: TCP
      targetPort: {{ .Values.nexus.port }}
  selector:
    app: {{ template "nexus.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.nexus.serviceType }}
